compatibility_date = "2025-10-02"
main = ".generated/workers.ts"
name = "cloesce"

[[d1_databases]]
binding = "db"
database_id = "replace_with_db_id"
database_name = "replace_with_db_name"

[[r2_buckets]]
binding = "bucket"
bucket_name = "replace-with-r2-bucket-name"

[vars]
myVariable = "default_string"
