[package]
name = "wrangler"
version = "0.0.1"
edition = "2024"

[dependencies]
ast = { path = "../ast" }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
