[package]
name = "common"
version = "0.0.1"
edition = "2024"

[dependencies]
hex = "0.4.3"
rustc-hash = "2.1.1"
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.14.1"
toml = { workspace = true }
