[package]
name = "workers"
version = "0.0.1"
edition = "2024"

[dependencies]
ast = { path = "../ast" }
tracing = { workspace = true }
pathdiff = { version = "0.2.3" }
indexmap = { workspace = true }

[dev-dependencies]
generator-test = { path = "../generator-test" }
