[package]
name = "cli"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
inquire = "0.9.1"
common = { path = "../common" }
d1 = { path = "../d1" }
client = { path = "../client" }
workers = { path = "../workers" }
wrangler = { path = "../wrangler" }
