[workspace]
resolver = "3"
members = ["cli", "common", "d1", "workers", "client", "wrangler"]

[workspace.dependencies]
indexmap = { version = "2.12.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
toml = "0.9.5"
