name: Deploy mdBook to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build mdBook and Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Install mdBook and plugins
        run: |
          cargo install mdbook
          cargo install mdbook-langtabs
      
      - name: Build mdBook
        run: |
          cd docs
          mdbook build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/book --project-name=cloesce
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}