name: Deploy docs

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build mdBook and Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Cache mdBook binaries
        uses: actions/cache@v4
        id: cache-cargo-bins
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bins-mdbook
      
      - name: Install mdBook and plugins
        if: steps.cache-cargo-bins.outputs.cache-hit != 'true'
        run: |
          cargo install mdbook
          cargo install mdbook-langtabs
      
      - name: Build mdBook
        working-directory: docs
        run: |
          mdbook-langtabs install
          mdbook build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/book --project-name=cloesce
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
