name: Deploy TypeDoc
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build TypeDoc and Deploy to Cloudflare Pages
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set version from tag
        working-directory: src/ts
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          npm version $VERSION --no-git-tag-version

      - name: Build Typedoc
        run: |
          npm install --prefix src/ts
          make build-typedoc

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/ts/build --project-name=cloesce-ts --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}